# Use postgres/example user/password credentials
version: '3.9'

services:

  postgres:
    image: postgres
    restart: always

    shm_size: 128mb

    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: dictionarygolang
    ports:
      - 5430:5432



  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: dictionary_server
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    working_dir: /app
    command: ["go", "run", "server/server.go"]


