package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"

	"github.com/staszkiet/DictionaryGolang/database"
	dbmodels "github.com/staszkiet/DictionaryGolang/database/models"
	"github.com/staszkiet/DictionaryGolang/graph/model"
)

// CreateWord is the resolver for the createWord field.
func (r *mutationResolver) CreateWord(ctx context.Context, polish string, translation model.NewTranslation) (bool, error) {
	DB := database.GetDBInstance()

	sentences := make([]dbmodels.Sentence, 0)

	for _, s := range translation.Sentences {
		sentences = append(sentences, dbmodels.Sentence{Sentence: s})
	}

	var convertedTranslations []dbmodels.Translation

	convertedTranslations = append(convertedTranslations, dbmodels.Translation{
		English:   translation.English,
		Sentences: sentences,
	})

	ret := &dbmodels.Word{
		Polish:       polish,
		Translations: convertedTranslations,
	}

	DB.Debug().Create(ret)
	return true, nil
}

// CreateSentence is the resolver for the createSentence field.
func (r *mutationResolver) CreateSentence(ctx context.Context, polish string, english string, sentence string) (bool, error) {
	var word dbmodels.Word
	DB := database.GetDBInstance()
	err := DB.Model(&dbmodels.Word{}).Preload("Translations.Sentences").Where("polish = ?", polish).First(&word).Error
	if err != nil {
		return false, err
	}
	for i, t := range word.Translations {

		if t.English == english {
			word.Translations[i].Sentences = append(word.Translations[i].Sentences, dbmodels.Sentence{Sentence: sentence})
		}
	}

	DB.Save(word)

	return true, nil
}

// CreateTranslation is the resolver for the createTranslation field.
func (r *mutationResolver) CreateTranslation(ctx context.Context, polish string, translation model.NewTranslation) (bool, error) {
	DB := database.GetDBInstance()

	var count int64
	var word dbmodels.Word
	sentences := make([]dbmodels.Sentence, 0)

	for _, s := range translation.Sentences {
		sentences = append(sentences, dbmodels.Sentence{Sentence: s})
	}

	err := DB.Model(&dbmodels.Word{}).Where("polish = ?", polish).Count(&count).Error
	if err != nil {
		return false, err
	}

	err = DB.Model(&dbmodels.Word{}).Preload("Translations.Sentences").Where("polish = ?", polish).First(&word).Error
	if err != nil {
		return false, err
	}

	word.Translations = append(word.Translations, dbmodels.Translation{
		English:   translation.English,
		Sentences: sentences,
	})

	DB.Save(word)

	return true, nil
}

// DeleteSentence is the resolver for the deleteSentence field.
func (r *mutationResolver) DeleteSentence(ctx context.Context, polish string, english string, sentence string) (bool, error) {
	var word dbmodels.Word
	DB := database.GetDBInstance()
	err := DB.Model(&dbmodels.Word{}).Preload("Translations.Sentences").Where("polish = ?", polish).First(&word).Error
	if err != nil {
		return false, err
	}

	var TranslationID uint

	for i, t := range word.Translations {

		if t.English == english {

			TranslationID = word.Translations[i].ID
			break
		}
	}

	if TranslationID == 0 {
		return false, fmt.Errorf("translation not found")
	}

	if err := DB.Where("translation_id = ? AND sentence = ?", TranslationID, sentence).Delete(&dbmodels.Sentence{}).Error; err != nil {
		return false, fmt.Errorf("failed to delete sentence: %v", err)
	}

	return true, nil
}

// DeleteTranslation is the resolver for the deleteTranslation field.
func (r *mutationResolver) DeleteTranslation(ctx context.Context, polish string, english string) (bool, error) {
	var word dbmodels.Word
	DB := database.GetDBInstance()

	err := DB.Model(&dbmodels.Word{}).Preload("Translations.Sentences").Where("polish = ?", polish).First(&word).Error
	if err != nil {
		return false, err
	}

	if err := DB.Where("word_id = ? AND english = ?", word.ID, english).Delete(&dbmodels.Translation{}).Error; err != nil {
		return false, fmt.Errorf("failed to delete translation: %v", err)
	}

	return true, nil
}

// DeleteWord is the resolver for the deleteWord field.
func (r *mutationResolver) DeleteWord(ctx context.Context, polish string) (bool, error) {
	var word dbmodels.Word
	DB := database.GetDBInstance()

	if err := DB.Preload("Translations.Sentences").Where("polish = ?", polish).First(&word).Error; err != nil {
		return false, err
	}

	if err := DB.Preload("Translations.Sentences").Delete(&word).Error; err != nil {
		return false, err
	}

	return true, nil
}

// UpdateWord is the resolver for the updateWord field.
func (r *mutationResolver) UpdateWord(ctx context.Context, polish string, newPolish string) (bool, error) {
	var word dbmodels.Word
	DB := database.GetDBInstance()
	err := DB.Model(&dbmodels.Word{}).Preload("Translations.Sentences").Where("polish = ?", polish).First(&word).Error
	if err != nil {
		return false, err
	}

	word.Polish = newPolish

	DB.Save(word)

	return true, nil
}

// UpdateTranslation is the resolver for the updateTranslation field.
func (r *mutationResolver) UpdateTranslation(ctx context.Context, polish string, english string, newEnglish string) (bool, error) {
	DB := database.GetDBInstance()

	var translation dbmodels.Translation

	err := DB.Joins("RIGHT JOIN words ON words.id = translations.word_id").
		Where("words.polish = ? AND translations.english = ?", polish, english).
		First(&translation).Error
	if err != nil {
		return false, err
	}

	err = DB.Model(&translation).Update("english", newEnglish).Error
	if err != nil {
		return false, err
	}

	return true, nil
}

// UpdateSentence is the resolver for the updateSentence field.
func (r *mutationResolver) UpdateSentence(ctx context.Context, polish string, english string, sentence string, newSentence string) (bool, error) {
	DB := database.GetDBInstance()

	var s dbmodels.Sentence

	err := DB.Joins("JOIN translations ON sentences.translation_id = translations.id").
		Joins("JOIN words ON words.id = translations.word_id").
		Where("words.polish = ? AND translations.english = ? AND sentences.sentence = ?", polish, english, sentence).
		First(&s).Error

	if err != nil {
		return false, err
	}

	err = DB.Model(&s).Update("sentence", newSentence).Error
	if err != nil {
		return false, err
	}

	return true, nil
}

// SelectWord is the resolver for the selectWord field.
func (r *queryResolver) SelectWord(ctx context.Context, polish string) (*model.Word, error) {
	var word dbmodels.Word
	DB := database.GetDBInstance()

	if err := DB.Preload("Translations.Sentences").Where("polish = ?", polish).First(&word).Error; err != nil {
		return nil, err
	}

	return dbmodels.DBWordToGQLWord(&word), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
