// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTranslation struct {
	English   string   `json:"english"`
	Sentences []string `json:"sentences"`
}

type Query struct {
}

type Sentence struct {
	Sentence string `json:"sentence"`
}

type Translation struct {
	English   string      `json:"english"`
	Sentences []*Sentence `json:"sentences"`
}

type Word struct {
	Polish       string         `json:"polish"`
	Translations []*Translation `json:"translations"`
}
