# Use postgres/example user/password credentials
version: '3.9'

services:

  postgres:

    image: postgres
    restart: always
    shm_size: 128mb

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"



  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dictionary_server
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    working_dir: /app
    command: ["go", "run", "server.go"]

volumes:
  pg_data:
    driver: local